- hosts: "{{ host }}"
  roles:
    - { role: deploy-app, tag: deploy-app, state: present }
    - { role: Datadog.datadog, sudo: yes }
    #- { role: deploy-monitors, tag: deploy-monitors, state: present }
    #- { role: integration-tests, tag: integration-tests }
    #- { role: deploy-monitors, tag: undeploy-monitors, state: absent }
  vars:
    datadog_config:
      tags: "env:meetup"
      log_level: INFO
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: My first test
            url: "http://localhost:{{ port }}/index.html"
            timeout: 2
