- hosts: "{{ host }}"
  roles:
    - { role: deploy-app, tag: deploy-app, state: started }
    - { role: integration-tests, tag: integration-tests }
    - { role: Datadog.datadog, tag: deploy-checks, sudo: yes }
    - { role: deploy-monitors, tag: deploy-monitors, state: present }
    - { role: deploy-monitors, tag: mute-monitors, state: mute }
    - { role: deploy-app, tag: undeploy-app, state: absent }
    - { role: deploy-monitors, tag: undeploy-monitors, state: absent }
  vars:
    test_url: "http://{{ host }}:{{ port }}/index.html"
    datadog_config:
      tags: "env:meetup"
      log_level: INFO
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: My first test
            url: "http://{{ host }}:{{ port }}/index.html"
            timeout: 2
